apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gkfn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0015-tenant/tkrw-pr712-0075-0015-app/devfile-sample-gkfn@sha256:2bbe83b9c0b5e6c4d6681f103e2f1ced2b974cf8f710ee65161fa4b534f89521
        name: my-nodejs
        resources: {}
status: {}
